server:
  port: 9090
my:
  custom:
    config:
      isServer: true  # 如果为 true，则启动 Server；如果为 false，则启动 Client
      timeFram: 10      #时间范围
      localHashMapMaxSize: 200000  # 用以比对的最大容量

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/block_chain
    username: root
    password: 199795
  rocketmq:
    topic: 
      hash: hash
      record: block_chain_record  
    # 指定使用 Proxy 的连接地址
    proxy:
      # Proxy 的地址，格式为 host:port
      server-address: 10.176.24.18:8081
      # 可选：Proxy 的命名空间，如果有配置
      namespace: your-namespace
      # 可选：是否启用 TLS 加密通信
      tls-enable: false
      # 可选：TLS 配置，例如证书路径等
      tls:
        ca-cert-path: path/to/ca.crt
        client-cert-path: path/to/client.crt
        client-key-path: path/to/client.key
    producer:
      group: your-producer-group # 生产者组名
      send-message-timeout: 3000 # 消息发送超时时间，单位为毫秒
      # 可选：重试次数
      retry-times-when-send-failed: 2

socket:
  server:
    ip: 127.0.0.1
    port: 9090
    uriForHash: "ws://10.176.24.18:9090/ws/hash"  # 服务器的 WebSocket URI
    uriForRecord: "ws://10.176.24.18:9090/ws/record"  # 服务器的 WebSocket URI
  client:
    ip: 127.0.0.1
    port: 9090
canal:
  server: 172.18.0.1   # 替换为你的Canal服务器地址
  port: 11111         # 替换为你的Canal服务器端口
  destination: example  # Canal实例名
  username:           # 如果需要用户名，填写；如果不需要，可以留空
  password:           # 如果需要密码，填写；如果不需要，可以留空
  subscription: ".*\\..*"  # 正则表达式，匹配要订阅的库和表，默认为订阅所有库表

